### ISSUE TITLE
Every tier shown on item tooltips is wrong

### ISSUE THREAD

**Issue by 0xe0d59** [TehCheat/PoEHUD#109]
The tier names are correct, but tier numbers are wrong. Can't tell how many good items I vendored because of this :(

For example: 
![Example](http://i.imgur.com/y4UwICa.png)

**Comment by TehCheat** [comment]
What's funny is you said every tier is wrong and the first one I looked at was the lightning resistance and it is accurate.  But yes, as a whole they are not terribly accurate.  I'll try and take a look to see exactly where these are coming from. I thought we were getting them straight from the ggpk file.

**Comment by zaafar** [comment]
@0xe0d59 can you run the game in x32 bit (direct x 9) and check if we are getting wrong over there too?

**Comment by 0xe0d59** [comment]
@TehCheat Well the lightning one is the only correct one there if you want me to be accurate. Yes, there are read from ggpk file, but they seem to be read wrong.

@zaafar 
x32 version shows correct tiers and names.

For example:
- x32
![x32](http://i.imgur.com/EDzqdXy.png)
- x64
![x64](http://i.imgur.com/AX73LSQ.png)

**Comment by zaafar** [comment]
@TehCheat I think i found the issue, but don't know how to fix it.

For example ( different item from what is show above):

when calculating "StunRecovery1" tier value ( which is 6 ) there is a new mod "StunRecoveryEssence7" which comes in the loop and due to which "StunRecovery1" get tier 7 rather than tier 6.

I am talking about following loop.
https://github.com/TehCheat/PoEHUD/blob/x64/src/Hud/AdvancedTooltip/ModValue.cs#L44

**Comment by TehCheat** [comment]
I mean if I were a betting man, I'd bet that's an address virtual table that was 4 bytes and is now 8 so it's probably tc + 8 * 4 * i, but I'm not gonna have a chance to examine it tonight.  It'll probably be ~16 hours until I can.  So if tc + 4 * i works, go for it.  Worst case scenario it's broken in a different way.  Best case it works.

**Comment by TehCheat** [comment]
OK, I lied.  Well, I didn't examine it, but I at least tried it really quickly.  And tc + 8 + 4 * i fails miserably.  Not sure all of the tiers are correct with tc + 4 * i (virile shows up as t3 on chest plates, but it's t5), but it's getting most of them right.  I think this is a problem with GGG not updating tiers in the ggpk file.  Nothing we can do about that.

**Comment by TehCheat** [comment]
Committed the fix and a rebuilt exe.

**Comment by zaafar** [comment]
About your virile thingy you are right ... because it's ggpk whos at fault, they didn't update old tiers tag/value.

[here](http://imgur.com/a/G34Rr)
As you can see rest of the mods i.e. IncreaseLife1-10 are loaded as tag=0: "default" and tagchance=1000 where as increaselife11,12 are loaded as tag=12: "body_armor" and tagchance=1000 for body armor and tag chance 0 for default....
