### ISSUE TITLE
Itemalert gone crazy

### ISSUE THREAD

**Issue by alexcrs** [TehCheat/PoEHUD#251]
After latest update Itemalert keeps showing ALL regular items, plus it's doing it with red text on white background, like it used to show divines and exalts...it's driving me crazy. PoE x64 windowed fullscreen dx11, neversink's latest semi-strict filter.
![item alert gone wild](https://user-images.githubusercontent.com/37373569/37407206-c7d28ef6-27a1-11e8-8a00-c9ca4aba6a1a.png)

**Comment by Quashdram** [comment]
Find all lines #Show and replace with # Show <-- notice the space between # and Show. It worked for me

**Comment by TehCheat** [comment]
Found the issue. It's because ANTLR4 is not handling the inline commenting on the Show/Hide statements and that is breaking everything. If you remove all of the comments after every show/hide, it should function normally. I'm going to try to find a solution, but so far I haven't found anything in regards to inline commenting. If I have to, I'll write a parser from scratch.

**Comment by DubyooC** [comment]
@Quashdram find the lines in what file, this is annoying lol.

**Comment by Quashdram** [comment]
@DubyooC oh sorry. Forgot to say it's in the loot filter :)

**Comment by DubyooC** [comment]
@TehCheat looks like its still going crazy after update ? Or am i doing something wrong?

**Comment by zaafar** [comment]
it's fixed now.
re-open this issue if it happens again.
