### ISSUE TITLE
Aspect Ratio Issue

### ISSUE THREAD

**Issue by Gonzoloe** [TehCheat/PoEHUD#254]
I use a custom resolution to force ultrawide.  Is there a way to customize the aspect ratio of the plugin?  I can't seem to find anything within the settings.

Thank you in advance.

**Comment by DetectiveSquirrel** [comment]
Aspect ration of what plugin?

**Comment by jetstrike** [comment]
I am working under the assumption he is having the same problem as me. The map icons and the AutoOpen plugin both have issues accurately detecting my location. The closer I get to objects the more accurate the icons become. It seems to me that this is caused by my 21:9 Aspect ratio. The closer I am to an object the more accurate it is. Here is an image showing the issue essentially everything is vertically misaligned. The poehud and Auto Open were working about a month ago but since i updated no dice. Auto open detect doors when I am far away and just causes me to run all over.
![map icons](https://user-images.githubusercontent.com/40432330/41664288-018ee034-746b-11e8-8e38-2a7f9e939c2e.png)


Imgur for larger image
https://imgur.com/9RTKoqV

**Comment by Painkiller1985** [comment]
I'm getting the same issue as Jetstrike, up down works, left right is off with the fairies
I'm running windows 7, windowed fullscreen, 1680 x 1050, both desktop and PoE are set to the same resolution

**Comment by Painkiller1985** [comment]
I also have an issue with the AutoOpen plugin not being able to work out where doors etc actually are (related?)

**Comment by TehCheat** [comment]
Make sure you have the latest (not from the releases page, from the main page, as the OC thread states in the first post, the releases page isn't always up to date).

**Comment by TehCheat** [comment]
I tested this on my machine and everything was normal. Things aren't perfect, but they aren't perfect at any aspect ratio (mostly because height isn't accounted for properly).
