### ISSUE TITLE
Overlay problem

### ISSUE THREAD

**Issue by CarryOnMyWayward** [TehCheat/PoEHUD#295]
Today i created new char and everytime it starts new incursion poehud overlay is desappeared. It is showing again after few seconds in incursion, but after exit it is desappearing again, and then it is showing only on loading screens, not ingame. Only found solution is restart poe.
There was no problems all night that i ran on other char about 50 incursions. I didn't changed anything, just created new char and this starts. Tried to reboot pc and download current code, nothing helped.

**Comment by TehCheat** [comment]
I believe this is related to post processing and entering/exiting incursions. Disable post processing in poe until we find a way to handle it.

**Comment by CarryOnMyWayward** [comment]
![image](https://user-images.githubusercontent.com/12736024/42035781-8e526144-7b05-11e8-9d94-8500d85cd741.png)
It is disabled all time. After leveling (don't know in wich moment exactly) problem solved, i hadn't it on maps. Started new char again - and this char have the same problem starting from first incursion on mud flats.

**Comment by TehCheat** [comment]
That's very helpful. I'll try and look into it.

**Comment by zaafar** [comment]
Implicit info: it’s steam. :)

**Comment by TehCheat** [comment]
Always annoying when people leave out details like that.

**Comment by Eric5766** [comment]
I had also been experiencing this at the start of the league and forgot about it when it stopped - Created a new character the other day and getting it again (Steam)

Had a quick look and currently level 15 and just finished act 1 and not getting this, don't seem to be getting Alva when I go back to the first few areas so can't test but it seems to either be something to do with the first few areas and incursions or player level?

**Comment by Eric5766** [comment]
I have found out where the issue occurs I think.

When you open the Incursion window by talking to Alva in an area the HUD seems to switch off for a second while the animation plays with the border flying over to the right to display the level preview with the bosses, then comes back on once the preview pops in, if you click enter incursion or close the window before letting the animation play out the HUD gets stuck in a switched off state and the only way to get it back is either relog and restart poehud or press V/talk to Alva and let the animation finish playing to restore it.

The reason this doesn't happen at higher levels is because at some point the animation doesn't play anymore and the incursion level preview is shown instantly when you open the window, probably to not waste peoples time who understand how it works.

**Comment by TehCheat** [comment]
Alva is no more, closing this issue. When it pops up in the future when Incursion is reintroduced, we'll have to take a look.
