### ISSUE TITLE
Cheating warning

### ISSUE THREAD

**Issue by POEzDD** [TehCheat/PoEHUD#300]
Just restarted my game to receive an ingame warning "You've been detected running cheating software"
I only use POEHUD and thought you guys and the devs should know.

**Comment by lab1992** [comment]
Same

Edit: More specificly, i launched the game then launch POEHud before pressing the log in button, the second i did, i got flagged with the message from OP. I've never launched poehud before logging in so i dont know if that effected anything but it seems too much a coincidence he and i came here at the same time but no one else coming is alittle weird.  Got this image on my alt account, But i didn't launch POEHud at all

![yellow](https://user-images.githubusercontent.com/34694162/42672189-637c15d6-8632-11e8-90d9-6f0ad8aaec75.png)

**Comment by CarryOnMyWayward** [comment]
Got the same issue. Game lagged and after few second i was disconnected. After clicking "login" i got this message. Using steam version. Poehud was in steam directory (not in poe directly, just "near" in steamapps/common) in "hud" folder. Renamed it now, but don't launh, waiting for some news about this warning.

**Comment by Eric5766** [comment]
If they aren't banning immediately sadly this might be their soft warning
that a crackdown on cheats is in the way.

I hope not but it could be RIP poehud, I don't have much interest in
playing the game without it as I like the quality of life too much, just
bought a bunch of new tabs as well.

**Comment by Eric5766** [comment]
Update to this after checking the thread on ownedcore, apparently they have
updated e their anticheat and will be banning people still using in the
next few days so stop all use for now unless you want to be banned

**Comment by DioBal** [comment]
Out of sheer curiosity, how are they detecting poehud?

**Comment by zaafar** [comment]
Using their anti cheat, of course.....

**Comment by markuszeller** [comment]
Started PoE today without having anything else started. Got the same message.

**Comment by CarryOnMyWayward** [comment]
https://www.ownedcore.com/forums/diablo-3/turbohud/turbohud-support/612776-how-protect-against-warden.html#post3710485 may this be used as a solution for us?

**Comment by DioBal** [comment]
What I am asking is how the anticheat works...

**Comment by Eric5766** [comment]
How it works is anyone's guess without looking into it.

It has always been said that poehud offers basically no protections and
they could detect at any time if they wanted to, probably because aside
from random window names it makes little to no effort to hide itself.

It's probably unlikely that anything can be done if they want to continue
aggressively combating cheats because you will always be risking a ban, and
as long as the program is open source and free it would be hard to stop the
bans.

It's a lot of effort playing cat and mouse with anticheats, if this is
going to be a continued effort and not just a banwave to prune/scare
cheaters then it might be tough luck for a while.

**Comment by TehCheat** [comment]
For now the solution to this seems to be running as a limited user which prevents detection in most cases. Are there things GGG could do to get around the limited user method? Sure. But until they do, I'm considering this closed.
