### ISSUE TITLE
Offsets for 3.5.0 need updated.

### ISSUE THREAD

**Issue by TehCheat** [TehCheat/PoEHUD#323]

**Comment by MWLVegas** [comment]
Apologies if this is the incorrect place for this; I was going to leave a new issue regarding minions showing as enemies on the map, and saw there was already one closed, mentioning offsets. I assume that's the problem now, so just adding here, rather than making a new issue, although you probably are already aware.

**Comment by TehCheat** [comment]
Yes, this is the proper location for it and we are aware of the problem. I looked at it and didn't have any luck, but I'm sure we'll get it figured out soon enough.
