### ISSUE TITLE
HUD's filter parser doesn't handle 'Identified' and 'Corrupted' keywords.

### ISSUE THREAD

**Issue by qqshka** [TehCheat/PoEHUD#59]
Could not used letest NeverSink's loot filter in item alert, you get exception.

**Comment by TehCheat** [comment]
The filter parser in HUD doesn't handle the keywords 'Identified' and 'Corrupted'.  You can comment them out of the filter you're using or use the built-in method.  Fixing this should be easy, but someone used Antlr to generate code, so it's a bit of a mess to cleanup.  Not sure how quickly I'll get to it (if ever).

**Comment by RolandSolymosi** [comment]
Hi, I tried a few thing with it, and I think it will need some serious reconstruction of the parser for this to work correctly. When I removed the not known tags from the filter, it was loaded without problem, but the filter was a mess. Every common item was purple and showed on the map (looked really funny after a breach), and most of the item types get switched around.

I don't know how much changed since the parser was created in the poe filter files, but the colors and notifications are not matching at all.

(Ofc it could be that I made something wrong when removed the Corrupted and Identified element, and it somehow made the items in these categories too generic, I'll plan to look on it more in details).

**Comment by TehCheat** [comment]
That sounds like Neversink's filter.  He puts unneeded borders on just about everything.

**Comment by zaafar** [comment]
@TehCheat should be closed now. 💃

**Comment by TehCheat** [comment]
Added the latest FilterParser to the project and this is no longer an issue.
