### ISSUE TITLE
DirectX 11 is not supported

### ISSUE THREAD

**Issue by Azcinor** [TehCheat/PoEHUD#62]

**Comment by zaafar** [comment]
it's supported, you need to change the branch to x64 and clone it from there.

**Comment by TehCheat** [comment]
I may rename the branch because the DirectX 11 option in PoE doesn't let the user know they're switching to 64 bit.  But like zaafar said, it is supported, you just have to use the right branch.

Closing...

**Comment by oneunderall** [comment]
I'm sorry if I sound stupid with this question, but how exactly do I change the branch to the x64 client? Do you mean the poehud exe code looks for the regular poe executable and not the poex64 executable? Do I have to edit something with poehuds code? Do I have to manually rename the poex64 client so that the one poehud searches for and finds is the directx11 version? Again apologies if this is more straightforward than I am making it. Thank you for your great work!

**Comment by Azcinor** [comment]
Hi.
On a poehud main github page you should choose right branch in top left corner from master to x64 and then download archive.

**Comment by TehCheat** [comment]
Here's a direct link to the x64 branch:
https://github.com/TehCheat/PoEHUD/tree/x64

**Comment by oneunderall** [comment]
Thank you guys! I tried both, the x64 version works just fine, but the one labeled Directx11 seems to have freezing and crashing issues on my laptop. Dell XPS17 8GB RAM and All the works if this matters at all. In any case, the one you've linked works great! Thanks again.

**Comment by TehCheat** [comment]
That's labeled "Garena DirectX 11".  That's for people that use Garena.
